name: flutter_woo_getx_learn
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 开启多语言配置
  flutter_localizations: 
    sdk: flutter
  
  cupertino_icons: ^1.0.5

  # getx 框架
  get: 4.6.5
  intl:  0.18.0
  package_info_plus: 4.1.0
  shared_preferences: 2.2.0
  dio: 5.3.2
  flutter_svg: 2.0.7
  badges: 3.1.1
  extended_image: 8.0.2
  flutter_screenutil: 5.9.0
  flutter_native_splash: 2.3.1
  carousel_slider: 4.2.1
  validatorless: 1.2.3
  pinput: 2.2.31
  flutter_easyloading: 3.0.5
  encrypt: 5.0.1
  pull_to_refresh: 2.0.0
  photo_view: 0.14.0
  dropdown_button2: 1.7.2
  another_xlider: 1.1.2
  # picker 选择器
  flutter_picker: 2.1.0
  # 底部弹出
  modal_bottom_sheet: 3.0.0-pre
  # permission 权限
  permission_handler: 10.4.3
  # 媒体选择
  wechat_assets_picker: 8.6.3
  wechat_camera_picker: 3.8.0
  shimmer: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # 图标生成
  #flutter_launcher_icons_maker: 0.10.2


flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: 'assets/icons/launcher_ios.png'
  image_path_android: "assets/icons/launcher_android.png"
  adaptive_icon_background: '#ffffff'
flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/launcher_android.png" 

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700